<a href="https://colab.research.google.com/github/aprendadatascience/projects/blob/master/Numpy_exercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 Qual a versao do Numpy instalada?

In [2]:
import numpy as np
print(np.__version__)

1.18.5


In [ ]:
!pip install numpy

#2 Como criar um array de 1 dimensão?

In [ ]:
arr = np.arange(6)


In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

#3 Crie um array boolean de dimensões 3×3, todos os itens devem ser True

3.1 Utilize a funcao full

In [ ]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3.2 Utilize a função ones

In [ ]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#4 Filtre itens de um array numpy utilizando uma determinada condição

In [ ]:
# Extrair somente os números ímpares 
# dado o array abaixo
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[ arr % 2 == 1]

array([1, 3, 5, 7, 9])

#5 Substitua determinados itens de um array numpy considerando uma condição

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7])

5.1 Substitua todos os números ímpares por -1

In [ ]:
arr[ arr %2 == 1] = -1

In [ ]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1])

#6 Substitua os itens ímpares do array arr por -1, mas sem modificar o array arr

In [ ]:
arr = np.arange(1,8)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
novo_arr = np.where(arr % 2 ==1, -1 , arr)

In [ ]:
novo_arr

#7 Alterando a forma/dimensão de um array numpy
7.1 Altere a dimensão de um array de 1D p/ um de 2D com 2 linhas


In [ ]:
# Array Inicial = array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(0,10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Array Desejado
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

In [ ]:
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
b=np.reshape(a,(2,-1))

In [ ]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#8 Encontrando itens em comum entre dois arrays numpy (intersecção)

In [ ]:
# Crie dois arrays com itens que se repitam
a = np.arange(1,10)
b = np.arange(8,14)

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b

array([ 8,  9, 10, 11, 12, 13])

In [ ]:
# encontre os itens que se repetem
np.intersect1d(a,b)

array([8, 9])

# 9 Removendo de um array itens que existem em outro array
9.1 - Remova do array a os itens que existem no array *b*

In [3]:
# Arrays de entrada com números
a = np.array([1,2,3,4,5])
b = np.array([1,3,5])
# Arrys de entrada com nomes
c = np.array(['honda','fiat','toyota','ford'])
d = np.array(['fiat','ford'])

In [4]:
np.setdiff1d(a,b)

array([2, 4])

In [5]:
np.setdiff1d(c,d)

array(['honda', 'toyota'], dtype='<U6')